export type TrainingType = "central" | "regional" | "special";

export type Training = {
  id: string;
  slug: string;
  name: string;
  type: TrainingType;
  typeLabel: string; // e.g., "কেন্দ্রীয়", "আঞ্চলিক", "রমাদান বিশেষ"
  duration: string;
  subject: string;
  targetGroup: string;
  location: string;
  schedule: string;
  fee: string;
  description: string;
  syllabus: string[];
  eligibility: string[];
};

export const trainings: Training[] = [
  // ==============================
  // Category 1: Central (Year-Round)
  // ==============================
  {
    id: "c1",
    slug: "central-nurani-shikkhok",
    name: "কেন্দ্রীয় নূরানী শিক্ষক প্রশিক্ষণ",
    type: "central",
    typeLabel: "কেন্দ্রীয়",
    duration: "৪০ দিন",
    subject: "নূরানী",
    targetGroup: "শিক্ষক",
    location: "বেফাক নিজস্ব প্রশিক্ষণ সেন্টার",
    schedule: "সারাবছর চলমান",
    fee: "অধিভুক্তদের জন্য বিনামূল্যে",
    description: "নূরানী পদ্ধতিতে শিশুদের কোরআন শিক্ষাদানের সর্বাধুনিক পদ্ধতির উপর ৪০ দিনের পূর্ণাঙ্গ প্রশিক্ষণ।",
    syllabus: ["নূরানী কায়দা", "মাখরাজ অনুশীলন", "শিশু মনস্তত্ত্ব", "শ্রেণি পরিচালনা", "আরবি হাতের লেখা"],
    eligibility: ["মাদ্রাসা পাশ", "কুরআন তিলাওয়াতে দক্ষতা", "বয়স: ন্যূনতম ২০ বছর"],
  },
  {
    id: "c2",
    slug: "central-hifz-shikkhok",
    name: "কেন্দ্রীয় হুফফাজুল কোরআন শিক্ষক প্রশিক্ষণ",
    type: "central",
    typeLabel: "কেন্দ্রীয়",
    duration: "৩০ দিন",
    subject: "হুফফাজ",
    targetGroup: "শিক্ষক",
    location: "বেফাক নিজস্ব প্রশিক্ষণ সেন্টার",
    schedule: "সারাবছর চলমান",
    fee: "অধিভুক্তদের জন্য বিনামূল্যে",
    description: "হুফফাযুল কোরআনের শিক্ষকদের জন্য আধুনিক পদ্ধতিতে পাঠদান, তাজবীদ ও মুখস্থ রাখার কৌশল বিষয়ে গভীর প্রশিক্ষণ।",
    syllabus: ["তাজবীদ ও তাহযীব", "শিক্ষাদান পদ্ধতি", "শ্রেণিকক্ষ ব্যবস্থাপনা", "হিফজ পদ্ধতি"],
    eligibility: ["হাফেজে কোরআন", "ন্যূনতম ২ বছরের অভিজ্ঞতা"],
  },

  // ==============================
  // Category 2: Regional (Year-Round)
  // ==============================
  {
    id: "r1",
    slug: "regional-dorsiyat-shikkhok",
    name: "দরসিয়াত শিক্ষক প্রশিক্ষণ",
    type: "regional",
    typeLabel: "আঞ্চলিক",
    duration: "৩–৭ দিন (সাধারণত ৫ দিন)",
    subject: "দরসিয়াত",
    targetGroup: "শিক্ষক",
    location: "আন্তজেলা মাদরাসাসমূহ",
    schedule: "সারাবছর বিভিন্ন সময়",
    fee: "বিনামূল্যে",
    description: "দরসিয়াত বিষয় পাঠদানের আধুনিক ও কার্যকর পদ্ধতির উপর সংক্ষিপ্ত আঞ্চলিক প্রশিক্ষণ।",
    syllabus: ["কিতাব শেখানোর পদ্ধতি", "ছাত্র মূল্যায়ন", "পাঠ পরিকল্পনা", "বিষয়ভিত্তিক ধারণা"],
    eligibility: ["দাওরায়ে হাদীস উত্তীর্ণ", "শিক্ষকতা পেশায় নিয়োজিত"],
  },
  {
    id: "r2",
    slug: "regional-dorsiyat-shikkhika",
    name: "দরসিয়াত শিক্ষিকা প্রশিক্ষণ",
    type: "regional",
    typeLabel: "আঞ্চলিক",
    duration: "৩–৭ দিন (সাধারণত ৫ দিন)",
    subject: "দরসিয়াত",
    targetGroup: "শিক্ষিকা",
    location: "আন্তজেলা মহিলা মাদরাসাসমূহ",
    schedule: "সারাবছর বিভিন্ন সময়",
    fee: "বিনামূল্যে",
    description: "মহিলা মাদ্রাসার শিক্ষিকাদের জন্য পৃথক পরিবেশে সংগঠিত দরসিয়াত ভিত্তিক বিশেষ প্রশিক্ষণ।",
    syllabus: ["কিতাব পদ্ধতি", "শ্রেণিকক্ষ ব্যবস্থাপনা", "ছাত্রী মূল্যায়ন"],
    eligibility: ["মহিলা দাওরা উত্তীর্ণ", "শিক্ষিকাগণ"],
  },
  {
    id: "r3",
    slug: "regional-calligraphy-students",
    name: "হস্তলিপি প্রশিক্ষণ (ছাত্রদের জন্য)",
    type: "regional",
    typeLabel: "আঞ্চলিক",
    duration: "৩–৭ দিন (সাধারণত ৫ দিন)",
    subject: "হস্তলিপি",
    targetGroup: "ছাত্র",
    location: "আন্তজেলা মাদরাসাসমূহ",
    schedule: "সারাবছর বিভিন্ন সময়",
    fee: "২০০ টাকা",
    description: "বিশেষভাবে মাদরাসা কেন্দ্রিক ছাত্রদের জন্য সুন্দর হস্তলিপি ও ক্যালিগ্রাফির বুনিয়াদি প্রশিক্ষণ।",
    syllabus: ["আরবি লিপি", "বাংলা ক্যালিগ্রাফি", "লেখার নিয়মকানুন"],
    eligibility: ["যে কোনো মাদরাসার ছাত্র"],
  },
  {
    id: "r4",
    slug: "regional-hifz-shikkhok",
    name: "হুফফাযুল কোরআন শিক্ষক প্রশিক্ষণ",
    type: "regional",
    typeLabel: "আঞ্চলিক",
    duration: "সাধারণত ৭ দিন",
    subject: "হুফফাজ",
    targetGroup: "শিক্ষক",
    location: "দেশের বিভিন্ন বড় মাদরাসায়",
    schedule: "মাঝে মাঝে",
    fee: "বিনামূল্যে",
    description: "আঞ্চলিকভাবে বড় মাদরাসাগুলোতে আয়োজিত হুফফাজ শিক্ষকদের ৭ দিনব্যাপী বিশেষ কোর্স।",
    syllabus: ["তাজবীদ", "হিফজ পরিচালনা", "উচ্চারণ ত্রুটি সংশোধন"],
    eligibility: ["হাফেজে কোরআন", "শিক্ষকতা পেশায় নিয়োজিত"],
  },
  {
    id: "r5",
    slug: "regional-nurani-shikkhok",
    name: "নূরানী শিক্ষক প্রশিক্ষণ",
    type: "regional",
    typeLabel: "আঞ্চলিক",
    duration: "সাধারণত ৩ দিন",
    subject: "নূরানী",
    targetGroup: "শিক্ষক",
    location: "দেশের বিভিন্ন বড় মাদরাসায়",
    schedule: "মাঝে মাঝে",
    fee: "বিনামূল্যে",
    description: "আঞ্চলিকভাবে আয়োজিত নূরানী পদ্ধতির উপর সংক্ষিপ্ত ও কার্যকর ৩ দিনের কোর্স।",
    syllabus: ["নূরানী কায়দা", "মাখরাজ", "শিশুদের পাঠদান পদ্ধতি"],
    eligibility: ["মাদরাসা পাশ"],
  },

  // ==============================
  // Category 3: Special (Shaban/Ramadan)
  // ==============================
  {
    id: "s1",
    slug: "special-dorsiyat-shikkhok",
    name: "কেন্দ্রীয় দরসিয়াত শিক্ষক প্রশিক্ষণ",
    type: "special",
    typeLabel: "রমাদান বিশেষ",
    duration: "২৩ দিন",
    subject: "দরসিয়াত",
    targetGroup: "শিক্ষক",
    location: "ঢাকার বড় কোনো আন্তমাদরাসায়",
    schedule: "শাবান ও রমাদান মাসে",
    fee: "ভর্তি ফি প্রযোজ্য",
    description: "বছরে একবার রমাদান উপলক্ষে আয়োজিত সর্ববৃহৎ দরসিয়াত শিক্ষক প্রশিক্ষণ মেলা।",
    syllabus: ["উচ্চতর কিতাব পদ্ধতি", "মনস্তাত্ত্বিক প্রশিক্ষণ", "ইসলামী আইন", "বক্তৃতা"],
    eligibility: ["দাওরায়ে হাদীস উত্তীর্ণ"],
  },
  {
    id: "s2",
    slug: "special-dorsiyat-shikkhika",
    name: "কেন্দ্রীয় দরসিয়াত শিক্ষিকা প্রশিক্ষণ",
    type: "special",
    typeLabel: "রমাদান বিশেষ",
    duration: "২২ দিন",
    subject: "দরসিয়াত",
    targetGroup: "শিক্ষিকা",
    location: "ঢাকার বড় কোনো মহিলা মাদরাসায়",
    schedule: "শাবান ও রমাদান মাসে",
    fee: "ভর্তি ফি প্রযোজ্য",
    description: "রমাদান উপলক্ষে দেশের স্বনামধন্য মহিলা মাদ্রাসায় আয়োজিত শিক্ষিকাদের সর্ববৃহৎ কোর্স।",
    syllabus: ["মহিলা মাদরাসা পরিচালনা", "উচ্চতর ফিকহ", "কিতাব পদ্ধতি"],
    eligibility: ["দাওরায়ে হাদীস উত্তীর্ণ"],
  },
  {
    id: "s3",
    slug: "special-hifz-central",
    name: "কেন্দ্রীয় হুফফাযুল কোরআন শিক্ষক প্রশিক্ষণ",
    type: "special",
    typeLabel: "রমাদান বিশেষ",
    duration: "১৫, ২৫, বা ৪০ দিন",
    subject: "হুফফাজ",
    targetGroup: "শিক্ষক",
    location: "বেফাক সেন্টার / বড় মাদরাসা / নিজামিয়া (ময়মনসিংহ)",
    schedule: "শাবান ও রমাদান মাসে",
    fee: "কোর্সভিত্তিক আলাদা ফি",
    description: "রমাদান উপলক্ষে একাধিক ব্যাচে (১৫ দিন, ২৫ দিন ও ৪০ দিন) হুফফাজ শিক্ষকদের জন্য বিশেষ আয়োজন।",
    syllabus: ["উচ্চতর তাজবীদ", "ক্বেরাত", "শিক্ষাদান পদ্ধতি"],
    eligibility: ["হাফেজে কোরআন", "ক্বেরাত জানা আবশ্যক"],
  },
  {
    id: "s4",
    slug: "special-nurani-central",
    name: "কেন্দ্রীয় নূরানী শিক্ষক প্রশিক্ষণ",
    type: "special",
    typeLabel: "রমাদান বিশেষ",
    duration: "১৫, ৩০, বা ৪০ দিন",
    subject: "নূরানী",
    targetGroup: "শিক্ষক",
    location: "বেফাক সেন্টার / ঢাকার বড় মাদরাসায়",
    schedule: "শাবান ও রমাদান মাসে",
    fee: "কোর্সভিত্তিক আলাদা ফি",
    description: "রমাদান উপলক্ষে নূরানী শিক্ষকদের জন্য একাধিক ব্যাচে আয়োজিত স্পেশাল প্রশিক্ষণ।",
    syllabus: ["নূরানী স্পেশাল কায়দা", "আরবি লেখা", "বাংলা ও অংক"],
    eligibility: ["মাদরাসা পাশ"],
  },
  {
    id: "s5",
    slug: "special-calligraphy-teachers",
    name: "হস্তলিপি প্রশিক্ষণ",
    type: "special",
    typeLabel: "রমাদান বিশেষ",
    duration: "৫ দিন বা ১৫ দিন",
    subject: "হস্তলিপি",
    targetGroup: "ছাত্র ও শিক্ষক",
    location: "বেফাক নিজস্ব প্রশিক্ষণ সেন্টার",
    schedule: "শাবান ও রমাদান মাসে",
    fee: "১০০০ টাকা",
    description: "বছরে একবার আয়োজিত বিশেষ ক্যালিগ্রাফি কোর্স। ৫ দিন ও ১৫ দিনের দুটি ব্যাচ থাকে।",
    syllabus: ["উচ্চতর আরবি ক্যালিগ্রাফি", "উর্দু ও ফার্সি লিপি", "বাংলা হাতের লেখা"],
    eligibility: ["মাদরাসার ছাত্র বা শিক্ষক"],
  },
  {
    id: "s6",
    slug: "special-literature-journalism",
    name: "সাহিত্য ও সাংবাদিকতা",
    type: "special",
    typeLabel: "রমাদান বিশেষ",
    duration: "১৫ দিন",
    subject: "সাহিত্য",
    targetGroup: "ছাত্র ও শিক্ষক",
    location: "ঢাকার বড় কোনো আন্তমাদরাসায়",
    schedule: "শাবান ও রমাদান মাসে",
    fee: "১৫০০ টাকা",
    description: "মাদরাসার ছাত্র ও শিক্ষকদের জন্য সাহিত্য চর্চা ও ইসলামী সাংবাদিকতার উপর বিশেষ কর্মশালা।",
    syllabus: ["প্রবন্ধ লেখা", "রিপোর্টিং", "ভাষাশৈলী", "মিডিয়া এথিক্স"],
    eligibility: ["মাদরাসার ছাত্র বা শিক্ষক", "লেখালিখির প্রাথমিক জ্ঞান"],
  },
  {
    id: "s7",
    slug: "special-english-language",
    name: "ইংরেজী ভাষা শিক্ষা",
    type: "special",
    typeLabel: "রমাদান বিশেষ",
    duration: "১৫ দিন",
    subject: "ভাষা",
    targetGroup: "ছাত্র ও শিক্ষক",
    location: "ঢাকার বড় কোনো আন্তমাদরাসায়",
    schedule: "শাবান ও রমাদান মাসে",
    fee: "১৫০০ টাকা",
    description: "মাদরাসার ছাত্র ও শিক্ষকদের জন্য স্পোকেন ইংলিশ ও বেসিক গ্রামারের উপর বিশেষ প্রশিক্ষণ।",
    syllabus: ["স্পোকেন ইংলিশ", "বেসিক গ্রামার", "শুনন ও কথন অনুশীলন"],
    eligibility: ["মাদরাসার ছাত্র বা শিক্ষক"],
  },
];

// Reusing centers from previous context (dummy data)
export const centers = [
  {
    id: "c1",
    name: "বেফাক প্রশিক্ষণ সেন্টার (সদর)",
    division: "ঢাকা",
    district: "ঢাকা",
    type: "central",
  },
  {
    id: "r1",
    name: "জামিয়া ইসলামিয়া দারুল উলুম",
    division: "ঢাকা",
    district: "গাজীপুর",
    type: "regional",
  },
  {
    id: "r2",
    name: "মাদরাসাতুল সুফফাহ",
    division: "চট্টগ্রাম",
    district: "চট্টগ্রাম",
    type: "regional",
  },
  {
    id: "r3",
    name: "জামিয়া ইমদাদিয়া",
    division: "রাজশাহী",
    district: "বগুড়া",
    type: "regional",
  },
  {
    id: "r4",
    name: "নিজামিয়া মাদরাসা",
    division: "ময়মনসিংহ",
    district: "ময়মনসিংহ",
    type: "regional",
  },
  {
    id: "r5",
    name: "জামিয়া আরাবিয়া",
    division: "খুলনা",
    district: "খুলনা",
    type: "regional",
  },
  {
    id: "r6",
    name: "দারুল উলুম মাদানিয়া",
    division: "সিলেট",
    district: "সিলেট",
    type: "regional",
  },
];

// Shared mock statistics
export const stats = {
  trainings: "১৪+",
  centers: "৫০+",
  districts: "৪০+",
  batches: "২৫০+",
  totalTrainings: "১৪+",
  totalCenters: "৫০+",
  totalTrainees: "লক্ষাধিক",
  trainees: "১,০০,০০০+",
};

// Global Site Info
export const siteInfo = {
  name: "বেফাকুল মাদারিসিল আরাবিয়া বাংলাদেশ",
  shortName: "বেফাক প্রশিক্ষণ",
  phone: "০১৭২২-৪৪৩৪৪৫",
  email: "training@wifaqbd.org",
  address: "সামাদনগর, যাত্রাবাড়ী, ঢাকা",
  facebook: "https://facebook.com/wifaqtadrib.bd",
};

export const notices = [
  {
    id: "n1",
    title: "৩৫তম কেন্দ্রীয় হুফফাযুল কোরআন শিক্ষক প্রশিক্ষণ কোর্সের ভর্তি বিজ্ঞপ্তি",
    date: "১৫ মে, ২০২৬",
    body: "৩৫তম কেন্দ্রীয় হুফফাযুল কোরআন শিক্ষক প্রশিক্ষণ কোর্সের ভর্তি শুরু হয়েছে। বিস্তারিত জানতে বিজ্ঞপ্তির পিডিএফটি পড়ুন।",
    category: "ভর্তি",
    file: "#",
  },
  {
    id: "n2",
    title: "দরসিয়াত শিক্ষক প্রশিক্ষণ (আঞ্চলিক) - চট্টগ্রাম কেন্দ্রের সময়সূচি পরিবর্তন প্রসঙ্গে",
    date: "১০ মে, ২০২৬",
    body: "অনিবার্য কারণবশত চট্টগ্রাম কেন্দ্রের সময়সূচি পরিবর্তন করা হয়েছে। বিস্তারিত নোটিশে দেখুন।",
    category: "জরুরি",
    file: "#",
  },
  {
    id: "n3",
    title: "৩৪তম ব্যাচের ফলাফল প্রকাশ ও সার্টিফিকেট বিতরণ বিজ্ঞপ্তি",
    date: "০৫ মে, ২০২৬",
    body: "৩৪তম ব্যাচের ফলাফল প্রকাশিত হয়েছে এবং আগামী সপ্তাহে সার্টিফিকেট বিতরণ করা হবে।",
    category: "ফলাফল",
    file: "#",
  },
];

export const events = [
  {
    id: "e1",
    slug: "e1",
    title: "জাতীয় হিফজুল কোরআন প্রতিযোগিতা - ২০২৬",
    date: "আগামী ২০ জুন, ২০২৬",
    venue: "বেফাক অডিটরিয়াম",
    type: "ইভেন্ট",
    image: "https://images.unsplash.com/photo-1597589827317-4c6d6e0a90bd?w=800&q=80",
    description: "সারাদেশের বাছাইকৃত হাফেজদের নিয়ে আয়োজিত সর্ববৃহৎ হিফজ প্রতিযোগিতা।",
  },
  {
    id: "e2",
    slug: "e2",
    title: "আঞ্চলিক প্রশিক্ষণ কেন্দ্র প্রধানদের বার্ষিক সম্মেলন",
    date: "২৫ জুলাই, ২০২৬",
    venue: "কেন্দ্রীয় কার্যালয়",
    type: "সম্মেলন",
    image: "https://images.unsplash.com/photo-1511895426328-dc8714191300?w=800&q=80",
    description: "সারাদেশের ৫০টিরও বেশি প্রশিক্ষণ কেন্দ্রের প্রধানদের নিয়ে কর্মশালা ও দিকনির্দেশনা মূলক অনুষ্ঠান।",
  },
  {
    id: "e3",
    slug: "e3",
    title: "ইসলামী ক্যালিগ্রাফি প্রদর্শনী ও প্রতিযোগিতা",
    date: "১০ আগস্ট, ২০২৬",
    venue: "ঢাকা",
    type: "প্রদর্শনী",
    image: "https://images.unsplash.com/photo-1597589827317-4c6d6e0a90bd?w=800&q=80",
    description: "দেশবরেণ্য ক্যালিগ্রাফারদের উপস্থিতিতে বিশেষ কর্মশালা।",
  },
];
