/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingsRouteImport } from './routes/trainings'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CentersRouteImport } from './routes/centers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdmissionRouteImport } from './routes/admission'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CodeRouteImport } from './routes/$code'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoticesIndexRouteImport } from './routes/notices.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as TrainingsSlugRouteImport } from './routes/trainings.$slug'
import { Route as NoticesIdRouteImport } from './routes/notices.$id'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTrainingsRouteImport } from './routes/_authenticated/admin.trainings'
import { Route as AuthenticatedAdminTrainingBatchesRouteImport } from './routes/_authenticated/admin.training-batches'
import { Route as AuthenticatedAdminTrainingAdmissionsRouteImport } from './routes/_authenticated/admin.training-admissions'
import { Route as AuthenticatedAdminSmsRouteImport } from './routes/_authenticated/admin.sms'
import { Route as AuthenticatedAdminShortLinksRouteImport } from './routes/_authenticated/admin.short-links'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminResultsRouteImport } from './routes/_authenticated/admin.results'
import { Route as AuthenticatedAdminNoticesRouteImport } from './routes/_authenticated/admin.notices'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin.messages'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'
import { Route as AuthenticatedAdminCentersRouteImport } from './routes/_authenticated/admin.centers'

const TrainingsRoute = TrainingsRouteImport.update({
  id: '/trainings',
  path: '/trainings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CentersRoute = CentersRouteImport.update({
  id: '/centers',
  path: '/centers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRoute = AdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesIndexRoute = NoticesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NoticesRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const TrainingsSlugRoute = TrainingsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TrainingsRoute,
} as any)
const NoticesIdRoute = NoticesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NoticesRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTrainingsRoute =
  AuthenticatedAdminTrainingsRouteImport.update({
    id: '/admin/trainings',
    path: '/admin/trainings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTrainingBatchesRoute =
  AuthenticatedAdminTrainingBatchesRouteImport.update({
    id: '/admin/training-batches',
    path: '/admin/training-batches',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTrainingAdmissionsRoute =
  AuthenticatedAdminTrainingAdmissionsRouteImport.update({
    id: '/admin/training-admissions',
    path: '/admin/training-admissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSmsRoute = AuthenticatedAdminSmsRouteImport.update({
  id: '/admin/sms',
  path: '/admin/sms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminShortLinksRoute =
  AuthenticatedAdminShortLinksRouteImport.update({
    id: '/admin/short-links',
    path: '/admin/short-links',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminResultsRoute =
  AuthenticatedAdminResultsRouteImport.update({
    id: '/admin/results',
    path: '/admin/results',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNoticesRoute =
  AuthenticatedAdminNoticesRouteImport.update({
    id: '/admin/notices',
    path: '/admin/notices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/admin/messages',
    path: '/admin/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/admin/events',
    path: '/admin/events',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCentersRoute =
  AuthenticatedAdminCentersRouteImport.update({
    id: '/admin/centers',
    path: '/admin/centers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/auth': typeof AuthRoute
  '/centers': typeof CentersRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/notices': typeof NoticesRouteWithChildren
  '/results': typeof ResultsRoute
  '/trainings': typeof TrainingsRouteWithChildren
  '/events/$id': typeof EventsIdRoute
  '/notices/$id': typeof NoticesIdRoute
  '/trainings/$slug': typeof TrainingsSlugRoute
  '/events/': typeof EventsIndexRoute
  '/notices/': typeof NoticesIndexRoute
  '/admin/centers': typeof AuthenticatedAdminCentersRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/admin/results': typeof AuthenticatedAdminResultsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/short-links': typeof AuthenticatedAdminShortLinksRoute
  '/admin/sms': typeof AuthenticatedAdminSmsRoute
  '/admin/training-admissions': typeof AuthenticatedAdminTrainingAdmissionsRoute
  '/admin/training-batches': typeof AuthenticatedAdminTrainingBatchesRoute
  '/admin/trainings': typeof AuthenticatedAdminTrainingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/auth': typeof AuthRoute
  '/centers': typeof CentersRoute
  '/contact': typeof ContactRoute
  '/results': typeof ResultsRoute
  '/trainings': typeof TrainingsRouteWithChildren
  '/events/$id': typeof EventsIdRoute
  '/notices/$id': typeof NoticesIdRoute
  '/trainings/$slug': typeof TrainingsSlugRoute
  '/events': typeof EventsIndexRoute
  '/notices': typeof NoticesIndexRoute
  '/admin/centers': typeof AuthenticatedAdminCentersRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/admin/results': typeof AuthenticatedAdminResultsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/short-links': typeof AuthenticatedAdminShortLinksRoute
  '/admin/sms': typeof AuthenticatedAdminSmsRoute
  '/admin/training-admissions': typeof AuthenticatedAdminTrainingAdmissionsRoute
  '/admin/training-batches': typeof AuthenticatedAdminTrainingBatchesRoute
  '/admin/trainings': typeof AuthenticatedAdminTrainingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$code': typeof CodeRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/auth': typeof AuthRoute
  '/centers': typeof CentersRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/notices': typeof NoticesRouteWithChildren
  '/results': typeof ResultsRoute
  '/trainings': typeof TrainingsRouteWithChildren
  '/events/$id': typeof EventsIdRoute
  '/notices/$id': typeof NoticesIdRoute
  '/trainings/$slug': typeof TrainingsSlugRoute
  '/events/': typeof EventsIndexRoute
  '/notices/': typeof NoticesIndexRoute
  '/_authenticated/admin/centers': typeof AuthenticatedAdminCentersRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/_authenticated/admin/results': typeof AuthenticatedAdminResultsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/short-links': typeof AuthenticatedAdminShortLinksRoute
  '/_authenticated/admin/sms': typeof AuthenticatedAdminSmsRoute
  '/_authenticated/admin/training-admissions': typeof AuthenticatedAdminTrainingAdmissionsRoute
  '/_authenticated/admin/training-batches': typeof AuthenticatedAdminTrainingBatchesRoute
  '/_authenticated/admin/trainings': typeof AuthenticatedAdminTrainingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$code'
    | '/about'
    | '/admission'
    | '/auth'
    | '/centers'
    | '/contact'
    | '/events'
    | '/notices'
    | '/results'
    | '/trainings'
    | '/events/$id'
    | '/notices/$id'
    | '/trainings/$slug'
    | '/events/'
    | '/notices/'
    | '/admin/centers'
    | '/admin/events'
    | '/admin/messages'
    | '/admin/notices'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/short-links'
    | '/admin/sms'
    | '/admin/training-admissions'
    | '/admin/training-batches'
    | '/admin/trainings'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$code'
    | '/about'
    | '/admission'
    | '/auth'
    | '/centers'
    | '/contact'
    | '/results'
    | '/trainings'
    | '/events/$id'
    | '/notices/$id'
    | '/trainings/$slug'
    | '/events'
    | '/notices'
    | '/admin/centers'
    | '/admin/events'
    | '/admin/messages'
    | '/admin/notices'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/short-links'
    | '/admin/sms'
    | '/admin/training-admissions'
    | '/admin/training-batches'
    | '/admin/trainings'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$code'
    | '/about'
    | '/admission'
    | '/auth'
    | '/centers'
    | '/contact'
    | '/events'
    | '/notices'
    | '/results'
    | '/trainings'
    | '/events/$id'
    | '/notices/$id'
    | '/trainings/$slug'
    | '/events/'
    | '/notices/'
    | '/_authenticated/admin/centers'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/notices'
    | '/_authenticated/admin/results'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/short-links'
    | '/_authenticated/admin/sms'
    | '/_authenticated/admin/training-admissions'
    | '/_authenticated/admin/training-batches'
    | '/_authenticated/admin/trainings'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CodeRoute: typeof CodeRoute
  AboutRoute: typeof AboutRoute
  AdmissionRoute: typeof AdmissionRoute
  AuthRoute: typeof AuthRoute
  CentersRoute: typeof CentersRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRouteWithChildren
  NoticesRoute: typeof NoticesRouteWithChildren
  ResultsRoute: typeof ResultsRoute
  TrainingsRoute: typeof TrainingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainings': {
      id: '/trainings'
      path: '/trainings'
      fullPath: '/trainings'
      preLoaderRoute: typeof TrainingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centers': {
      id: '/centers'
      path: '/centers'
      fullPath: '/centers'
      preLoaderRoute: typeof CentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission': {
      id: '/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$code': {
      id: '/$code'
      path: '/$code'
      fullPath: '/$code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices/': {
      id: '/notices/'
      path: '/'
      fullPath: '/notices/'
      preLoaderRoute: typeof NoticesIndexRouteImport
      parentRoute: typeof NoticesRoute
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/trainings/$slug': {
      id: '/trainings/$slug'
      path: '/$slug'
      fullPath: '/trainings/$slug'
      preLoaderRoute: typeof TrainingsSlugRouteImport
      parentRoute: typeof TrainingsRoute
    }
    '/notices/$id': {
      id: '/notices/$id'
      path: '/$id'
      fullPath: '/notices/$id'
      preLoaderRoute: typeof NoticesIdRouteImport
      parentRoute: typeof NoticesRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/trainings': {
      id: '/_authenticated/admin/trainings'
      path: '/admin/trainings'
      fullPath: '/admin/trainings'
      preLoaderRoute: typeof AuthenticatedAdminTrainingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/training-batches': {
      id: '/_authenticated/admin/training-batches'
      path: '/admin/training-batches'
      fullPath: '/admin/training-batches'
      preLoaderRoute: typeof AuthenticatedAdminTrainingBatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/training-admissions': {
      id: '/_authenticated/admin/training-admissions'
      path: '/admin/training-admissions'
      fullPath: '/admin/training-admissions'
      preLoaderRoute: typeof AuthenticatedAdminTrainingAdmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/sms': {
      id: '/_authenticated/admin/sms'
      path: '/admin/sms'
      fullPath: '/admin/sms'
      preLoaderRoute: typeof AuthenticatedAdminSmsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/short-links': {
      id: '/_authenticated/admin/short-links'
      path: '/admin/short-links'
      fullPath: '/admin/short-links'
      preLoaderRoute: typeof AuthenticatedAdminShortLinksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/results': {
      id: '/_authenticated/admin/results'
      path: '/admin/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AuthenticatedAdminResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/notices': {
      id: '/_authenticated/admin/notices'
      path: '/admin/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AuthenticatedAdminNoticesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/centers': {
      id: '/_authenticated/admin/centers'
      path: '/admin/centers'
      fullPath: '/admin/centers'
      preLoaderRoute: typeof AuthenticatedAdminCentersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminCentersRoute: typeof AuthenticatedAdminCentersRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminNoticesRoute: typeof AuthenticatedAdminNoticesRoute
  AuthenticatedAdminResultsRoute: typeof AuthenticatedAdminResultsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminShortLinksRoute: typeof AuthenticatedAdminShortLinksRoute
  AuthenticatedAdminSmsRoute: typeof AuthenticatedAdminSmsRoute
  AuthenticatedAdminTrainingAdmissionsRoute: typeof AuthenticatedAdminTrainingAdmissionsRoute
  AuthenticatedAdminTrainingBatchesRoute: typeof AuthenticatedAdminTrainingBatchesRoute
  AuthenticatedAdminTrainingsRoute: typeof AuthenticatedAdminTrainingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminCentersRoute: AuthenticatedAdminCentersRoute,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminNoticesRoute: AuthenticatedAdminNoticesRoute,
  AuthenticatedAdminResultsRoute: AuthenticatedAdminResultsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminShortLinksRoute: AuthenticatedAdminShortLinksRoute,
  AuthenticatedAdminSmsRoute: AuthenticatedAdminSmsRoute,
  AuthenticatedAdminTrainingAdmissionsRoute:
    AuthenticatedAdminTrainingAdmissionsRoute,
  AuthenticatedAdminTrainingBatchesRoute:
    AuthenticatedAdminTrainingBatchesRoute,
  AuthenticatedAdminTrainingsRoute: AuthenticatedAdminTrainingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface NoticesRouteChildren {
  NoticesIdRoute: typeof NoticesIdRoute
  NoticesIndexRoute: typeof NoticesIndexRoute
}

const NoticesRouteChildren: NoticesRouteChildren = {
  NoticesIdRoute: NoticesIdRoute,
  NoticesIndexRoute: NoticesIndexRoute,
}

const NoticesRouteWithChildren =
  NoticesRoute._addFileChildren(NoticesRouteChildren)

interface TrainingsRouteChildren {
  TrainingsSlugRoute: typeof TrainingsSlugRoute
}

const TrainingsRouteChildren: TrainingsRouteChildren = {
  TrainingsSlugRoute: TrainingsSlugRoute,
}

const TrainingsRouteWithChildren = TrainingsRoute._addFileChildren(
  TrainingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CodeRoute: CodeRoute,
  AboutRoute: AboutRoute,
  AdmissionRoute: AdmissionRoute,
  AuthRoute: AuthRoute,
  CentersRoute: CentersRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRouteWithChildren,
  NoticesRoute: NoticesRouteWithChildren,
  ResultsRoute: ResultsRoute,
  TrainingsRoute: TrainingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
